sudo: required
services:
    - docker

before_install:
    - docker build -t ashwinathappan/docker-react -f Dockerfile.dev .

script:
    - docker run ashwinathappan/docker-react npm run test -- --coverage