name: Docker CI-CD

env:
  EB_S3_BUCKET_NAME  : "elasticbeanstalk-us-east-1-496016226872"
  EB_APPLICATION_NAME: "Docker"
  EB_ENVIRONMENT_NAME: "Docker-env"
  DEPLOY_PACKAGE_NAME: "deploy.zip"
  AWS_REGION_NAME    : "us-east-1"


on: [push, pull_request]

jobs:
  CI-CD:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        run : docker build -t ashwinathappan/docker-react -f Dockerfile.dev .

      - name: Run the Docker image
        run : docker run -e CI=true ashwinathappan/docker-react npm run test

      - name: Generate deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      - name: Deploy to ElasticBeanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          existing_bucket_name: ${{ env.EB_S3_BUCKET_NAME }}
          region: ${{ env.AWS_REGION_NAME }}
          version_label: ${{ github.sha }}
          deployment_package: ${{ env.DEPLOY_PACKAGE_NAME }}

